//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.PracticaIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "PracticaIPS_DSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"PracticaIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PracticaIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PracticaIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PracticaIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PracticaIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPracticaIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PracticaIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string PracticaIPSPackageId = "69f593bf-6986-412f-9870-bddbf6aeb270";
		
		// Editor factory identifier
		public const string PracticaIPSEditorFactoryId = "c424d206-2c22-4936-bb98-9db8ae2a5514";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PracticaIPSModelExplorerToolWindowId = "05d41726-1b0c-49bb-bb9f-e0a81648046a";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.PracticaIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PracticaIPSCommandSetId = "813d4107-6efc-4f76-9927-4142beff226a";
	}
}